version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend/btp-meeting-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/btp-meeting-ui:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    env_file:
      - ./frontend/btp-meeting-ui/.env
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  data:
  node_modules:

